import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from "next/font/google";
import LayoutComp from "@/components/LayoutComp/LayoutComp";

const roboto = Roboto({
    weight: ["400", "500", "700"],
    subsets: ["latin"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "Autorail Monitor",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-BR" className={roboto.className}>
            <head>
                {/* Adicionando Font Awesome via CDN */}
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />
                <link rel="icon" href="/icone-aumo.svg" />
            </head>
            <body>
                <LayoutComp>{children}</LayoutComp>
            </body>
        </html>
    );
}
